name: Deploy to GH Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: yarn
    - name: Build & Deploy
      env:
          MY_DEPLOY_KEY: ${{ secrets.MY_DEPLOY_KEY }}
      run: |
        git config --global user.email "aguretsvlad@gmail.com"
        git config --global user.name "vladagurets"
        git remote set-url origin https://${{ $MY_DEPLOY_KEY }}@github.com/vladagurets/sort-visualizer.git
        yarn build
        echo 1
        echo $MY_DEPLOY_KEY
        echo 2
        echo 2
        echo 2
        echo 2
        echo 2
        yarn deploy
